# Generated by Django 5.0.6 on 2024-05-18 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(db_index=True, max_length=14, unique=True)),
                ('rg', models.CharField(max_length=9, unique=True)),
                ('data_nascimento', models.DateField()),
                ('contato', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('genero', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=12)),
                ('logradouro', models.CharField(max_length=50)),
                ('numero_casa', models.IntegerField()),
                ('bairro', models.CharField(max_length=50)),
                ('pis', models.CharField(max_length=20, unique=True)),
                ('serie', models.CharField(max_length=20)),
                ('uf', models.CharField(max_length=2)),
                ('numeracao_ctps', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(related_name='usuario_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='usuario_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=100, unique=True)),
                ('autor', models.CharField(max_length=100)),
                ('reu', models.CharField(max_length=100)),
                ('instancia', models.CharField(max_length=100)),
                ('forum', models.CharField(max_length=100)),
                ('valor_da_causa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assunto', models.CharField(max_length=500)),
                ('cliente', models.ForeignKey(db_column='cpf_cliente', on_delete=django.db.models.deletion.CASCADE, to='task.cliente', to_field='cpf')),
                ('clientes', models.ManyToManyField(related_name='processos', to='task.cliente')),
            ],
        ),
    ]
