# Generated by Django 5.0.6 on 2024-05-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(db_index=True, max_length=14, unique=True)),
                ('rg', models.CharField(max_length=9, unique=True)),
                ('data_nascimento', models.DateField()),
                ('contato', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('genero', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=12)),
                ('logradouro', models.CharField(max_length=50)),
                ('numero_casa', models.IntegerField()),
                ('bairro', models.CharField(max_length=50)),
            ],
        ),
    ]
