# Generated by Django 5.0.6 on 2024-05-22 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Andamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=100)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andamentos', to='task.processo')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_tarefa', models.CharField(max_length=100, unique=True)),
                ('data_base', models.DateField()),
                ('data_fatal', models.DateField()),
                ('data_final', models.DateField()),
                ('situacao', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.cliente')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.processo')),
                ('processos', models.ManyToManyField(related_name='tarefas', to='task.processo')),
            ],
        ),
    ]
