# Generated by Django 5.0.6 on 2024-06-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='clientes',
        ),
        migrations.AlterField(
            model_name='processo',
            name='valor_da_causa',
            field=models.CharField(max_length=10),
        ),
    ]
