# Generated by Django 5.0.6 on 2024-06-11 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_processo_clientes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='cliente',
            field=models.ForeignKey(db_column='cpf_cliente', on_delete=django.db.models.deletion.CASCADE, to='task.cliente', to_field='cpf'),
        ),
        migrations.DeleteModel(
            name='Andamento',
        ),
    ]
