# Generated by Django 5.0.6 on 2024-06-11 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_tarefa_cliente_delete_andamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='cliente',
        ),
    ]
