# Generated by Django 5.0.6 on 2024-06-11 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_rename_data_final_tarefa_data_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='processo',
            field=models.ForeignKey(db_column='numero_p', on_delete=django.db.models.deletion.CASCADE, to='task.processo', to_field='numero_processo'),
        ),
    ]
